- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: yes

- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.gpg
    mode: '0644'

- name: Add Grafana repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Ensure Grafana is running
  systemd:
    name: grafana-server
    enabled: yes
    state: started