---
- name: Deploy Nginx in EC2
  hosts: web_servers
  become: true
  tasks:
    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


    - name: Copy index file for Ubuntu
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: ansible_distribution == "Ubuntu"
      tags: index


    - name: Ensure Nginx is running
      systemd:
        name: nginx
        enabled: yes
        state: started
      when: ansible_distribution == "Ubuntu"
      tags: nginx
